---
title: "Identifying companies and financial actors exposed to marine tipping points"
author: |
    | \small Juan C. Rocha^1^, Jean-Baptiste Jouffray^1^, Paula A. Sánchez^1,2^, Victor Galaz^1^
    | \footnotesize ^1^Stockholm Resilience Centre, Stockholm University
    | \footnotesize ^2^Germany?
    | \small \texttt{\href{mailto:juan.rocha@su.se}{\nolinkurl{juan.rocha@su.se}}}
output:
  pdf_document:
    dev: pdf
    keep_tex: yes
    toc: no
    latex_engine: xelatex
  rtf_document:
    toc: no
  word_document:
csl: /Users/juanrocha/Documents/styles/apa.csl
#bibliography: refs.bib
citecolor: blue
documentclass: article
font: Arial
fontsize: 10pt
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{dcolumn, rotating, longtable, lineno, float, array, tabularx, inputenc}
- \setmainfont{Arial}
- \renewcommand{\abstractname}{}
- \graphicspath{{figures/}}
- \usepackage[margin=2.5cm]{geometry}
- \linenumbers
- \usepackage{setspace}
---

# Notes

- Author order tbd
- Target journal: Nature family?, GEC, Finance journal? ~ 4000w, 4 figs, 40refs
- Word budget
    - Intro: 1000w
    - Method: 800w
    - Results: 1000w
    - Discussion: 800w
    - Conclusions: 400w


\pagebreak

\begin{abstract}

  

\end{abstract}

# Introduction

- Marine ecosystems are expected to undergo large biological reorganization and regime shifts that can affect primary productivity and other ecosystem services.
- Exposure to such regime shifts are mediated by pressures on marine ecosystems, from climate change, fishing pressure, or pollution.
    - Marine heatwaves
    - Destabilization of upwellings
- Companies and financial actors are part of the problem by being partly responsible for the causes of ecological degradation. These actors are in turn exposed to the risk of regime shifts and decline of ecosystem services.
- RQ: **Which financial actors are exposed to regime shift risks, and thus have the agency to avoid them or can play a role in navigating transformations?**

# Methods

_Case studies:_ To that end, we first identified areas of the oceans exposed to potential regime shifts. Marine heatwaves are expected to increase in frequency and intensity [@Frolicher:2018dc; @Frolicher:2018cm], with stark consequences for the economy of companies, regions and nations depending on the ocean productivity [@Smith_2021]. For example, the Gulf of Alaska experienced a heat anomaly known as the Blob in 2014-2019, impacting a fishery valued at US\$103M / year, with a estimated loss of US\$24.4M, while harmful algae blooms costed US\$40M loss in tourist spending in the coast of Washington in 2015 [@Smith_2021]. Other areas with high vulnerability to heatwaves include the tropical Pacific ocean, the Caribbean sea, the North coasts of Australia, the Eastern China sea and the West Pacific ocean [@Smith_2021]. Proxies of resilience loss in the oceans have been calculated using early warnings to the proximity of tipping points in time series data of primary productivity [@Rocha_2022]. Areas showing strong signals or resilience loss include the Easter Indo-Pacific and the tropical Easter Pacific oceans.

- Maybe a figure Map with the case studies

_Companies_: Based on the geographic exposure to regime shifts, we then identified fishing companies operating in these regions. We used permits and licences issued in Alaska by the National Oceanic and Atmospheric Administration in the United States ([NOAA](https://www.fisheries.noaa.gov/alaska/commercial-fishing/permits-and-licenses-issued-alaska)) to list companies with permits to fish Alaskan pollock, one of the most profitable resources in the region. We used fishing permits issued by the _Servicio nacional de Pesca y Acuicultura_ or the National Fishing and Aquaculture authority of Chile, to companies with the purpose of harvesting anchovies and sardines.

- check with Paula, we should have Peru as well
- what to do with tuna? we only have O

_Financial actors_: Using the [Orbis](https://login.bvdinfo.com/R0/Orbis) database we extracted the shareholder information for publicly listed companies (names and approximate ratio of ownership), their number of employees, and annual revenues. We complemented the data when possible with information on debt and liquidity from the [Eikon refinitiv](https://eikon.refinitiv.com) database. Unfortunately these data sources are not open access and their terms of service forbids sharing accessed data with third parties. Both of them were accessed through research subscriptions by the home institution.

_Systemic risk exposure_:

# Results



# Discussion

- Limitation: publicly listed companies, and legal fisheries.

# Conclusion


## Acknowledgements



# References {.unnumbered}

::: {#refs}
:::

\pagebreak



# Supplementary Material {#sec:SM}

