---
title: "Notes"
output: html_notebook
author: Juan Rocha
editor_options: 
  chunk_output_type: inline
---

# Notes

**241112**

- MHW did not have strong clear effects on single species models (some sp decline while other thrive). But sp can move, primary producers don't move. MHW so far have been contained to limited areas, but projections suggest larger scale possibly longer than the ability of fish to move away.
- 

**sometime**

- Make sure to read for the paper:
    - Malin Pinsky paper on MHW [X]
    - Latest Kroodsma paper on fishing fleets []


**240321**

- The lists of owners have numbers because at some point we decided to search for OrbisIDs instead of company names. The company names results were ambiguous and Bianca did some manual work to match ambiguous names to IDs that were of companies fishing. That is why we have some owners coded as orbis ID instad of compnay names.
- `guos` is not unique because the same company with the same `orbis_id` can have multiple GUOs over time. We do not distinguish them.

**240220**

- All data from Carmine is now added to the database. Bianca manually annotated vessels for whom we could not find orbis ID automatically (N=411). This added observations to our GUO, revenues and shareholders. However, from Orbis although the company exist, there is still missing 374 companies shareholder data, 286 companies revenues data, and 143 companies GUOs data. All data is now combined and saved in `data/cleaned_data_231214.Rda`

**240216**

- A sample of ~10k mine names were downloaded from Orbis over Xmas break. That took ~10days of computing time. The problem is many mines are not easily matchable with records in Orbis. For a few of them one can be sure due to the economic activity field in Orbis (but not always recorded), or because the mine name contains the product they exploit: diamonds, gold, etc. However, for many of them we don't know if the company info downloaded is actually a mine.
- Idea: one could circumvent this by hard coding the verification: it is mine if the econ activity is recorded, or if the name contains the metal. Other options are if the company is based on the country where the coordinates from Maus are recorded... buiding up a confidence score or something similar. Once solved, we can go ahead and download more. Bear in mind it takes long time to do so.
- Marine paper: I need to download the missing Carmine companies and then merge with complete dataset, so scripts 15 and 16 with missing data corrected by Bianca.


**231213**

- Discussion? stranded assets - link to literature and who is exposed to them
- High net worth individuals: merging the marine data, EID, fossil fuels, mining.

*230816*

- Created a report with preliminary data from Lloyds and Orbis. 
- Data from Kroodsma was used to identify >16k vessels fishing in places prone to tipping
- Places were extracted from Smith heatwaves methodology replicated on NOAAs temp data and my dataset on resilience loss
- > 2000 companies identified, and >700 shareholders, but networks are too sparse

*20230202*

- Download the Fishing effort dataset used in Krodsma y Carmine. It contain GPS traces of >70k vessels with some information about ownership. Carmine has addional owners identified but only for high seas vessels.
- Problem: we only have ocean disclosure project data for pacific tuna, which are mainly retailiers and very few companies. Excludes China and all the key actors of that area. Go with the fine grane data, much better.

- create a spatial mask to filter the vessels of interest: this is, regions of the world with exposure to tipping points: my map + heatwaves papers.


To-do list:

1. Compute the import / export ratio per country
2. Same at commodity level: are there commodities that are purely trade driven?
3. ~~Explore Paula's file: rank countries per number of companies on high risk~~
4. ~~Extract main commodities~~
5. Characterize missing values: where are they missing (countries) and what vars are not very useful?
6. ~~Construct networks between countries and corporations weighted by subsidiaries?~~

Exponential random graph models:
- Include world governance indicators
- Inequality
- Triangles? Feedforward triangles -> theory on instability?
- Valued ergm with number of companes count on link weight?
- Create network of investors combined for all cases
- Create investor - country (where investors are based)
- The later two should provide descriptive stats.

Experiment with the HH-Index: https://en.wikipedia.org/wiki/Herfindahl–Hirschman_index

Cannot make it bipartite because:
The following vertices appear in both columns:
	- Bnp Paribas
	- Oji Holdings Corporation

One could force it to be bipartite by changing name according to category. Once bipartite, use the one mode projections to calculate network statistics more relevant for influence. For example a weighted betweenness or something like that. 

### EGRMs

- use constraints on degree: keep degrees constant. But not sure how to code it
- Play with control features:
        - MCMCLE.maxit = < 60 which is the current default (how do I get the defaults?)
        
        
        
### Lloyds

- P & I club is insurance
- Download Carmine SM it has fishing vessel numbers and owners.
opitions AHS markets: IMO global record of fishing vessles,. globalrecord.fao.org/vessels

- Overlay management areas RFMO regional fisheries managmenet organisations maps...regulatory body that groups the relevant countries that need to cooperate to handle potential shifts in the fisheries.



## Readings

*[Hobday et al 2023 Nature](https://doi.org/10.1038/d41586-023-02730-2)*

_"Worryingly, the climate crisis could eventu- ally cause oceans to reach a permanent heat- wave state relative to historical baselines11, and some regions might no longer support certain species and ecosystems. The eco- systems that emerge might not operate and respond to warmer waters in ways that can be anticipated12."_

*Carmine 2020 OneEarth*
- Combining satellite data with other public databases, our analysis showed 1,120 corporate actors owned 2,482 high seas fishing vessels in 2018 ($2/3 of total detected ves- sels). The industry is consolidated with 100 companies representing 36% of high seas fishing effort.
- China, the fishing entity of Taiwan, Japan, Indonesia, Spain, and the Republic of Korea accounting for 77% of the identified global high seas fishing fleet and 80% of all high seas fishing effort for 2016.
- Global Fishing Watch (GFW): gps records per vessel, 3.5k vessels in 2018
- One of the main challenges in this analysis was determining the ultimate parent company. [we target that challenge]
- At present, about 55,000 vessels have been identified with AIS as actively fishing in EEZs in 2018.
- The fishing vessels with AIS data represent a fraction of the world’s total motorized fishing fleets of length greater than 12 m, estimated to be 300,000 vessels,

Method:
-  To avoid counting fishing hours associated with falsified AIS signals, we excluded, from this analysis, vessels whose supposedly unique AIS identities were simultaneously shared between two or more vessels over 72 h in total during 2018.
- GFW’s vessel database attributed owner information to about 1,199 vessels relying mostly on publicly available data including IMO’s shipping information system.

*kroodsma 2018 Science*

- more than 70,000 identified fishing vessels that are 6 to 146 m in length. 
- Global hot spots of fishing effort were seen in the northeast Atlantic (Europe) and northwest Pacific (China, Japan, and Russia) and in upwelling regions off South America and West Africa (Fig. 1A).
- most nations fished predominantly within
their own EEZ, with five flag states (China, Spain, Taiwan, Japan, and South Korea) accounting for more than 85% of observed fishing effort on the high seas
- modern fishing is like other forms of mass production that are partially insulated from natural cycles and are instead shaped by policy and culture.

**Frölicher et al 2018 Nature**

- Heatwaves are events when SST exceed the 99th percentile with respect to daily satalite observations for a 30yr period. 
- "Between 1982 and 2016, we detect a doubling in the number of MHW days, and this number is projected to factor of 16 for global warming of 1.5 degrees Celsius relative to preindustrial levels and by a factor 23 for global warming of 2.0 degrees Celsius"...3.1C will be 41x times more MHW.
- The modeling results when compared with satellite observations gives confidence to the spatial extend of predictions, less so to their duration, cumulative mean intensity or absolute spatial extend.
- at 3.5C warming, a one-in-a-hundred-days event will become a one-in-three-days event!
- Excellent paper!

**Smith et al 2021 Science**

- " MHW events exceed US\$800 million in direct losses or >US\$3.1 billion in indirect losses of ecosystem services for multiple years"
- "discrete warming events, marine heatwaves (MHWs), have increased substantially, with a rise in global annual MHW days of 54% over the past century"
- " an event is considered a MHW if it lasts for 5 or more days, with tem- peratures warmer than the 90th percentile based on a 30-year historical climatology (41)."

